### ISSUE TITLE
Code scaffold (Projektsetup, Socketinfrastruktur)

### ISSUE THREAD

**Issue by mad-mike** [Ypsiliform/code#1]

**Comment by schoendort** [comment]
I created a maven project with 3 artifacts:

- agent, this will be a executable jar
- mediator, this will be packed in a war-deployment, so you can run it on a java ee7 server (I've tested it on wildfly 9.0.2.final)
- messages, this is a project for shared code between agent and mediator

**Comment by mad-mike** [comment]
closed with PR #4
